# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a25731535dd4c46afd5225e10f1587c4df3a58c193191f4d55b29d355d8509d3e836e60b836cec803e1e2323d19558c43bb58f75a1632f5407e145b4c216caae

test:
  secret_key_base: 7f537fb62b2382e655990744a45fb035d8531877399eb571cb8e48b203e50bd92fb150ad37e077277909dcbbc57eb5e3bd0b7f73e37b7ffd88ebb7bc07ad5533

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
